### ISSUE TITLE
Obrazek znaleziska po lewej

### ISSUE THREAD

**Issue by rlesniak** [tentin-quarantino/wykop-the-best-style#6]
Można przywrócić żeby obrazek byl po lewej stronie. Kod:

```css
[data-night-mode] .home section.link-block > section > article {
  padding: 12px 24px 12px 260px !important;
}
[data-night-mode] .home section.link-block > section > article figure {
  right: auto !important;
  left: 16px;
  height: 154px !important;
  top: 12px !important;
}
```

Efekt 
![image](https://user-images.githubusercontent.com/13970783/213302759-350b454a-bfa9-4f9a-8e63-0c3a87a203dd.png)
